### PR TITLE
[ FIX ] Handling of Signed VarInts

### LINKED ISSUE #241: [BUG] Negative number handling in wallet wire encoding
## Bug Description

WalletWireTransceiver is using `-1`, e.g. [here](https://github.com/bitcoin-sv/ts-sdk/blob/65d799b/src/wallet/substrates/WalletWireTransceiver.ts#L153). But `Utils.varIntNum()` seems to assume only positive numbers are passed in [here](https://github.com/bitcoin-sv/ts-sdk/blob/547e36f/src/primitives/utils.ts#L519). When trying to output this data as hex using `Utils.toHex()` [here](https://github.com/bitcoin-sv/ts-sdk/blob/master/src/primitives/utils.ts#L22) it generates invalid hex with `-1` in it, e.g. `6f6e3a-1-10101`.

## Steps to Reproduce

```js
import {WalletWireTransceiver} from "./src/wallet";
import WalletWire from "./src/wallet/substrates/WalletWire.js";
import * as Utils from "./src/primitives/utils.js";

class WalletWireTemp implements WalletWire {
    async transmitToWallet(message: number[]): Promise<number[]> {
        console.log(Utils.toHex(message));
        return [];
    }
}

const run = async () => {
    const wire = new WalletWireTemp()
    const transceiver = new WalletWireTransceiver(wire)

    await transceiver.createAction({
        description: 'Test action description',
        outputs: [{
            lockingScript: '00',
            satoshis: 1000,
            outputDescription: "Test output description",
        }],
    })
}

run().then()
```

## Expected Behavior

Wallet wire messages should encode to valid hex.

## Actual Behavior

Invalid hex is generated.
```
0100175465737420616374696f6e206465736372697074696f6e-1-1010100fde80300-1-1-1-1-1-100
```

## Stack Traces or Screenshots

See description.

## Environment

- Present in latest `v1.4.11`

## Additional Information

### PR DESCRIPTION
**Pull request by sirdeggen**
## Description of Changes

Updates how Negative value VarInts are handled throughout the stack.

## Linked Issues / Tickets

Closes #241 

## Testing Procedure

Describe the tests you've added or any testing steps you've taken.

- [ ] I have added new unit tests
- [x] All tests pass locally
- [ ] I have tested manually in my local environment

## Checklist:

- [x] I have performed a self-review of my own code
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have updated `CHANGELOG.md` with my changes
- [x] I have run `npm run doc` and `npm run lint` one final time before requesting a review
- [x] I have fixed all linter errors to ensure these changes are compliant with `ts-standard`
- [x] I have run `npm version patch` so that my changes will trigger a new version to be released when they are merged

### CODE REVIEW

File: src/primitives/utils.ts [hunk 1]
```diff
@@ -801,3 +810,6 @@ export const minimallyEncode = (buf: number[]): number[] => {
   // If we found the whole thing is zeros, then we have a zero.
   return []
 }
+
+const OverflowInt64 = new BigNumber('9223372036854775808') // 2^63
```
Comment (jchavannes) [inline src/primitives/utils.ts:814]: This could be updated to use `new BigNumber(2).pos(new BigNumber(63))`.

**Comment by sirdeggen** [comment]
It should be noted that anyone using `readVarIntNum` is going to be confused when they try to read a very large number and it comes out as negative, since signed is default.
